### ISSUE TITLE
when i send url with "-" error ocurred

### ISSUE THREAD

**Issue by sonickseven** [LevelNewsOrg/url-metadata#10]
When i send this url to lib, this never respond https://github.com/comprobamos/dashboard-comprobamos/wiki/Guia-de-comandos

I used your lib from 1 year ago and this is a first error i all that time

**Comment by laurengarcia** [comment]
I think the problem here was actually #4 which is now merged and fixed. Please update from npm to version 2.1.8:

https://www.npmjs.com/package/url-metadata
