### ISSUE TITLE
Can't get metadata

### ISSUE THREAD

**Issue by kristoff2016** [LevelNewsOrg/url-metadata#13]
Hello,
thank you for nice plugin. 
When I used your example url I get nothing 

`author: ""
availability: ""
canonical: ""
description: ""
image: ""
keywords: ""
og:description: ""
og:determiner: ""
og:image: ""
og:image:height: ""
og:image:secure_url: ""
og:image:type: ""
og:image:width: ""
og:locale: ""
og:locale:alternate: ""
og:site_name: ""
og:title: ""
og:type: ""
og:url: ""
price: ""
priceCurrency: ""
source: "wearechange.org"
title: null
url: "https://wearechange.org/hero-bullhorn-reads-internet-julian-assange-sidewalk"`

Any ideas ?

thank you

**Comment by waseemshahwan** [comment]
+1
