### ISSUE TITLE
unable to get og:image preview from below links

### ISSUE THREAD

**Issue by riksof-haris** [LevelNewsOrg/url-metadata#15]
Hi Guys,
Thank u so much for the your great work.

I m getting data from **aliexpress** but unable to get **og:image.**

https://www.aliexpress.com/item/Stylish-Four-Seasons-Running-Shoes-For-Men-Air-Breathable-Lightweight-Sports-Shoes-Black-Red-Male-Gym/32917513610.html?spm=a2g01.12638254.p99adbb.11.34cd65014C46Px&gps-id=5868145&scm=1007.20675.119049.0&scm_id=1007.20675.119049.0&scm-url=1007.20675.119049.0&pvid=7fcd74eb-3208-4232-938c-cf0f6bf02ee5

Also unable to get item data from **amazon.com**

https://www.amazon.com/Curve-Road-Julianne-MacLean-ebook/dp/B079R8DY6F/ref=redir_mobile_desktop/145-1419762-9539363?_encoding=UTF8&ref_=mh_s9_acsd_ri_c_x_5_w

Can you please help me find out what is the issue? is there something which i m missing or its module issue?

**Comment by laurengarcia** [comment]
Will take a look in the coming days.

**Comment by laurengarcia** [comment]
The first url seems to be fine and is returning an og:image for me locally:

![image](https://user-images.githubusercontent.com/1278969/55280347-d23f6500-52e1-11e9-87b4-d863fc8b15f4.png)

**Comment by laurengarcia** [comment]
The second one seems to be because Amazon explicitly blocks scrapers. See points 13-19 in this explainer: https://blog.hartleybrody.com/scrape-amazon/

Good luck. If you need anything else just reopen.

**Comment by riksof-haris** [comment]
why other channels like slack, whatsapp able to fetch the amazon data?
