### ISSUE TITLE
Getting Cors Error

### ISSUE THREAD

**Issue by maks112v** [LevelNewsOrg/url-metadata#17]
Access to fetch at 'https://dribbble.com/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by mamta-vkl** [comment]
I'm also getting the CORS error, can anyone please suggest a solution for that?

**Comment by sukitz** [comment]
> I'm also getting the CORS error, can anyone please suggest a solution for that?

I worked 'https://cors-anywhere.herokuapp.com/+url'

example
`https://cors-anywhere.herokuapp.com/https://www.foo.com`

**Comment by capcons** [comment]
I am using this in lambda function and use it as api using api gateway and giving me error  has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

and ERROR Error: Uncaught (in promise): HttpErrorResponse: {"headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"status":0,"statusText":"Unknown Error",


How to resolve it..

**Comment by laurengarcia** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
