### ISSUE TITLE
Don't display falsey values 

### ISSUE THREAD

**Issue by mayeaux** [LevelNewsOrg/url-metadata#19]
What do you think about having an option whereby you can not have the fields displayed if they have no value? That would be useful in the code I'm writing. I could use a helper of course but just wanted to float the idea for being built into the module, thanks.

**Comment by laurengarcia** [comment]
Hm... I'm concerned that its a minor change with very little value-add for users, that may trip people up who are already using the module in the designed way... Suggest you filter empty fields out on your side.

**Comment by mayeaux** [comment]
No problem figured I'd mention it, thanks for the module!
