### ISSUE TITLE
Certain URLs cause Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ronidavelman** [LevelNewsOrg/url-metadata#6]
For example, this url: https://www.fintrux.com/home/doc/whitepaper.pdf

domutils/lib/traversal.js:22
exports.getName = function(elem){
                          
RangeError: Maximum call stack size exceeded
    at Object.exports.getName

This also occurs with some of the other urlmetadata modules on npm, specifically node-MetaInspector

**Comment by c0rnonthec0bb** [comment]
This appears to still be an issue

**Comment by mauronr** [comment]
> This appears to still be an issue

It is. https://lnkd.in/gVeYnv7 is an example that causes this error.
